--------------------------------------------------------
--  File created - วันพุธ-มีนาคม-30-2559   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TDCS_APPRENTICE
--------------------------------------------------------

  CREATE TABLE "TDCS"."TDCS_APPRENTICE" 
   (	"APT_ID" NUMBER(6,0), 
	"APT_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TDCS.TDCS_APPRENTICE
SET DEFINE OFF;
Insert into TDCS.TDCS_APPRENTICE (APT_ID,APT_NAME) values (1,'ฝึกงาน');
Insert into TDCS.TDCS_APPRENTICE (APT_ID,APT_NAME) values (2,'สหกิจศึกษา');
--------------------------------------------------------
--  DDL for Index JHRM_APPRENTICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDCS"."JHRM_APPRENTICE_PK" ON "TDCS"."TDCS_APPRENTICE" ("APT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TDCS_APPRENTICE
--------------------------------------------------------

  ALTER TABLE "TDCS"."TDCS_APPRENTICE" ADD CONSTRAINT "JHRM_APPRENTICE_PK" PRIMARY KEY ("APT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TDCS"."TDCS_APPRENTICE" MODIFY ("APT_ID" NOT NULL ENABLE);
